routes/web.php
<?php

use App\Http\Controllers\CardController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CardController::class, 'index'])->name('home');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
    'role:admin'
])->group(function () {
    Route::get('/colors/add', [ColorController::class, 'create'])->name('colors.add');
    Route::get('/colors/delete/{color}', [ColorController::class, 'destroy'])->name('colors.delete');
    Route::post('/colors/store', [ColorController::class, 'store'])->name('colors.store'); 

    Route::get('/cards/add', [CardController::class, 'create'])->name('cards.add');
    Route::get('/cards/delete/{card}', [CardController::class, 'destroy'])->name('cards.delete');
    Route::post('/cards/store', [CardController::class, 'store'])->name('cards.store');    
    
    Route::post('/comments/add', [CommentController::class, 'store'])->name('comments.add');
    Route::get('/comments/delete/{comment}', [CommentController::class, 'destroy'])->name('comments.delete');

    Route::resource('/users', UserController::class)->names('users');
});

Route::get('/colors/{color}', [ColorController::class, 'show'])->name('colors.show');
Route::get('/colors', [ColorController::class, 'index'])->name('colors.index');

Route::get('/cards/{card}', [CardController::class, 'show'])->name('cards.show');
Route::get('/cards', [CardController::class, 'index'])->name('cards.index');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles;
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'banned',
        'kicked_to',
    ];

    protected $dates = [
        'banned',
        'kicked_to',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array<int, string>
     */
    protected $appends = [
        'profile_photo_url',
    ];

    
    /**
     * Get the cards for the user.
     */
    public function cards()
    {
        return $this->hasMany(Card::class, 'user_id', 'id');
    }
    
    /**
     * Get the cards for the user.
     */
    public function comments()
    {
        return $this->hasMany(Comment::class, 'user_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

use function Psy\debug;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(20);

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return redirect()->route('users.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->show($user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $msg = 'Roles actualizados. ';

        $roles = array_keys($request->roles);
        if($user->hasRole('admin') && !isset($request->roles['admin']) && $user->id == auth()->id){//evito que un admin se pueda quitar los permisos de administración a sí mismo
            $roles[] = 'admin';
            $msg .= 'Recuerda que no puedes quitarte el rol de admin a ti mismo';
        }

        $user->syncRoles($roles);

        return redirect()->route('users.show', $user)->with('success', $msg);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //$user->delete();
        return redirect()->route('users.index')->with('success', "Usuario {$user->name} eliminado.");
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/user/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Usuarios') }}
        </h2>
    </x-slot>

    <div>
        <div class="max-w-7xl mx-auto py-10 px-6 lg:px-8">
            @if (Session::has('success'))
                <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md"
                    role="alert">
                    <div class="flex">
                        <div class="py-1">
                            <svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 20 20">
                                <path
                                    d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z" />
                            </svg>
                        </div>

                        <div>
                            <p class="font-bold">Información</p>
                            <p class="text-sm">
                                {{ Session::get('success') }}
                            </p>
                        </div>
                    </div>
                </div>
            @endif

            @if ($users->count() > 0)

                <table class="table-auto w-full my-4 border-collapse text-sm" style="border: 1px solid #e5e7eb">
                    <thead>
                        <tr>
                            <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-left">
                            </th>
                            <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-left">
                                Nombre</th>
                            <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-left">
                                Email</th>
                            <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-center">
                                Registro</th>
                            {{-- <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-center">
                                Suspendido hasta</th>
                            <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-center">
                                Baneado el</th> --}}
                            <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-right">
                                Admin</th>
                            <th
                                class="border-b dark:border-slate-600 font-medium p-4 text-slate-400 dark:text-slate-200 text-right">
                                Borrar</th>
                        </tr>
                    </thead>

                    <tbody class="bg-white dark:bg-slate-800">
                        @foreach ($users as $user)
                            <tr class="even:bg-gray-200">
                                <td class="text-right p-3">
                                    <img data-bs-toggle="tooltip" title="{{ $user->name }}"
                                        alt="Foto de {{ $user->name }}" src="{{ $user->profile_photo_url }}"
                                        class="w-5 h-5 rounded-full" 
                                        />
                                    </td>
                                <td class="text-left p-3">
                                    <a 
                                        class="hover:text-gray-500 hover:underline transition-all transform duration-700"
                                        href="{{ route('users.show', $user->id) }}">
                                        {{ $user->name }}
                                    </a>
                                </td>
                                <td class="text-left p-3">
                                    <a
                                        class="hover:text-gray-500 hover:underline transition-all transform duration-700"
                                        href="mailto:{{ $user->email }}">
                                        {{ $user->email }}
                                    </a>
                                </td>
                                <td class="text-center p-3">
                                    {{ \Carbon\Carbon::parse($user->created_at)->format('j-m-Y H:i') }}</td>
                                {{-- <td class="text-center p-3">
                                    {{ $user->kicked_to ? \Carbon\Carbon::parse($user->kicked_to)->format('j-M-Y H:i:s') : ' - ' }}
                                </td>
                                <td class="text-center p-3">
                                    {{ $user->banned ? \Carbon\Carbon::parse($user->banned)->format('j-M-Y H:i:s') : ' - ' }}
                                </td> --}}
                                <td class="text-right p-3">
                                    {{ $user->hasRole('admin') ? 'Sí' : 'No' }}
                                </td>
                                <td class="text-right p-3">
                                    <form action="{{ route('users.destroy', $user->id) }}">
                                        @csrf
                                        @method('DELETE')

                                        <button onclick="deleteConfirm(event, this)"
                                            class="inline-flex items-center px-4 py-2 bg-red-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 active:bg-red-900 focus:outline-none focus:border-red-900 focus:ring focus:ring-gray-300 disabled:opacity-25 transition">
                                            Borrar
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $users->links() }}
            @else
                <p>{{ __('¡No hay usuarios!') }}</p>
            @endif
        </div>
    </div>
</x-app-layout>

resources/views/user/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Usuario') }}
        </h2>
    </x-slot>

    <div>
        <div class="w-full max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="bg-white shadow-md rounded px-8 p-6 pb-8 mb-4">
                <div class="flex items-center mb-3">
                    <div
                        class="mr-3 inline-flex items-center justify-center rounded-full bg-gray-100 text-white flex-shrink-0">
                        <img src="{{ $user->profile_photo_url }}" data-bs-toggle="tooltip" title="{{ $user->name }}"
                            class="w-12 h-12 rounded-full" />
                    </div>
                    <h1 class="text-gray-800 text-5xl title-font font-bold">
                        {{ $user->name }}
                    </h1>
                </div>

                <div class="w-full mx-auto mt-4 rounded">
                    <!-- Tabs -->
                    <ul id="tabs" class="inline-flex w-full px-1 pt-2 ">
                        <li class="px-4 py-2 -mb-px font-semibold text-gray-800 border-b-2 border-indigo-400 rounded-t opacity-50">
                            <a id="cards-tab" href="#cards">Tarjetas</a>
                        </li>

                        <li class="px-4 py-2 font-semibold text-gray-800 rounded-t opacity-50">
                            <a id="comments-tab" href="#comments">Comentarios</a>
                        </li>

                        <li class="px-4 py-2 font-semibold text-gray-800 rounded-t opacity-50">
                            <a id="permissions-tab" href="#permissions">Permisos</a>
                        </li>
                    </ul>

                    <!-- Tab Contents -->
                    <div id="tab-contents">
                        <div id="cards" class="hidden p-4">
                            <x-show-user-cards :user-id="$user->id" :items="1" />
                        </div>
                        <div id="permissions" class="hidden p-4">
                            <x-show-user-permissions :user-id="$user->id" />
                        </div>
                        <div id="comments" class="hidden p-4">
                            <x-show-user-comments :user-id="$user->id" :items="2" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="module">
        let tabsContainer = document.querySelector("#tabs");
        let tabTogglers = tabsContainer.querySelectorAll("a");

        tabTogglers.forEach(function(toggler) {
            toggler.addEventListener("click", function(e) {
                e.preventDefault();

                let tabName = this.getAttribute("href");
                localStorage.setItem('selectedTab', tabName);

                let tabContents = document.querySelector("#tab-contents");

                for (let i = 0; i < tabContents.children.length; i++) {

                    tabTogglers[i].parentElement.classList.remove("border-indigo-400", "border-b", "-mb-px", "opacity-100");
                    tabContents.children[i].classList.remove("hidden");
                    if ("#" + tabContents.children[i].id === tabName) {
                        continue;
                    }
                    tabContents.children[i].classList.add("hidden");

                }

                e.target.parentElement.classList.add("border-indigo-400", "border-b-2", "-mb-px", "opacity-100");
            });
        });

        
        let tab = localStorage.getItem('selectedTab');
        console.log(tab);
        if(tab !== null){
            document.getElementById(tab.replaceAll('#', '') + '-tab').click();
        }
        else{
            document.getElementById("cards-tab").click();
        }
    </script>
</x-app-layout>